### ISSUE TITLE
Clicking on the Explore hyperlink in the breadcrumb menu gives a white page

### ISSUE THREAD

**Issue by h0t1ce** [clidey/whodb#52]
![broken_breadcrumb_link](https://github.com/user-attachments/assets/a737f5e8-e8cd-451e-9ff2-d7b9e9ebe423)

```javascript
main.c0ac5221.js:2  Uncaught TypeError: Cannot read properties of undefined (reading 'Name')
    at ahe (main.c0ac5221.js:2:5582158)
    at ms (main.c0ac5221.js:2:2627640)
    at xa (main.c0ac5221.js:2:2641866)
    at Sl (main.c0ac5221.js:2:2688174)
    at bc (main.c0ac5221.js:2:2676397)
    at vc (main.c0ac5221.js:2:2676325)
    at mc (main.c0ac5221.js:2:2676188)
    at rc (main.c0ac5221.js:2:2672968)
    at lc (main.c0ac5221.js:2:2673359)
    at zo (main.c0ac5221.js:2:2613951)
 ```

**Comment by hkdeman** [comment]
Thank you for pointing this out! This will be fixed in the upcoming filters PR: https://github.com/clidey/whodb/pull/53
